{% set name = "jupyter-sphinx" %}
{% set package = "jupyter_sphinx" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ package }}-{{ version }}.tar.gz
  sha256: 37fc9408385c45326ac79ca0452fbd7ae2bf0e97842d626d2844d4830e30aaf2

build:
  number: 1
  noarch: python
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - ipython
    - ipywidgets >=7.0.0
    - nbconvert >=5.5
    - nbformat
    - sphinx >=2

test:
  imports:
    - jupyter_sphinx

about:
  home: https://github.com/jupyter/jupyter-sphinx/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx extension for rendering of Jupyter interactive widgets.
  doc_url: https://jupyter-sphinx.readthedocs.io/

extra:
  recipe-maintainers:
    - akhmerov
    - chrisjsewell
