{% set name = "jupyter-sphinx" %}
{% set package = "jupyter_sphinx" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ package }}-{{ version }}.tar.gz
  sha256: c4caf8bbf2be6edfe0319aa76127d17fdbe6927c8189cda2d6ac59c01f38404b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipython
    - ipywidgets >=7.0.0
    - nbconvert >=5.5
    - nbformat
    - sphinx >=2,<4

test:
  imports:
    - jupyter_sphinx

about:
  home: https://github.com/jupyter/jupyter-sphinx/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx extension for rendering of Jupyter interactive widgets.
  doc_url: https://jupyter-sphinx.readthedocs.io/

extra:
  recipe-maintainers:
    - akhmerov
    - chrisjsewell
